import type { Product } from "../types";
import { enrichSeedProduct } from "./product-catalog";
import { SEED_PRODUCT_IDS } from "./product-ids";

export { SEED_PRODUCT_IDS, isSeedProductId } from "./product-ids";

const SEED_TIMESTAMP = "2026-07-02T18:00:00.000Z";

const BASE_DEFAULT_PRODUCTS: Product[] = [
  {
    id: SEED_PRODUCT_IDS.cliniqueAllAboutCleanSoap,
    name: "All About Clean Liquid Facial Soap Mild",
    brand: "Clinique",
    category: "cleanser",
    ingredients: [
      "Water",
      "Sodium Laureth Sulfate",
      "Cocamidopropyl Hydroxysultaine",
      "Lauramidopropyl Betaine",
      "Aloe Barbadensis Leaf Juice",
      "Sucrose",
      "Sodium Hyaluronate",
      "Tocopheryl Acetate",
    ],
    activeIngredients: ["sucrose", "hyaluronic acid", "aloe"],
    usageGuide:
      "Use twice daily. Lather a dime-sized amount with lukewarm water, massage over makeup-free face and neck for 30–60 seconds, rinse, and pat dry. Follow with toner and moisturizer.",
    frequency: "daily",
    timeOfDay: "any",
    notes: "Clinique Skin Type 2 (dry combination). Step 1 of the 3-Step System.",
    isSeed: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: SEED_PRODUCT_IDS.cliniqueClarifyingLotion2,
    name: "Clarifying Lotion 2",
    brand: "Clinique",
    category: "exfoliant",
    ingredients: [
      "Water",
      "Alcohol Denat.",
      "Glycerin",
      "Hamamelis Virginiana (Witch Hazel) Extract",
      "Acetyl Glucosamine",
      "Sodium Hyaluronate",
      "Trehalose",
      "Butylene Glycol",
    ],
    activeIngredients: ["salicylic acid", "witch hazel", "acetyl glucosamine"],
    usageGuide:
      "Use twice daily after cleansing. Saturate a cotton pad and sweep gently over face and neck, avoiding eyes and lips. Follow immediately with moisturizer.",
    frequency: "daily",
    timeOfDay: "any",
    notes: "For dry combination skin. Liquid exfoliator with BHA; Step 2 of the 3-Step System.",
    isSeed: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: SEED_PRODUCT_IDS.cliniqueDramaticallyDifferentLotion,
    name: "Dramatically Different Moisturizing Lotion+",
    brand: "Clinique",
    category: "moisturizer",
    ingredients: [
      "Water",
      "Glycerin",
      "Petrolatum",
      "Urea",
      "Sodium Hyaluronate",
      "Hordeum Vulgare (Barley) Extract",
      "Cucumis Sativus (Cucumber) Fruit Extract",
      "Helianthus Annuus (Sunflower) Seedcake",
      "Sesamum Indicum (Sesame) Oil",
    ],
    activeIngredients: ["urea", "glycerin", "hyaluronic acid"],
    usageGuide:
      "Apply twice daily to face and throat after cleanser and exfoliator. Spread evenly; absorbs quickly. Can layer under SPF in the morning or treatments at night.",
    frequency: "daily",
    timeOfDay: "any",
    notes: "Barrier-strengthening lotion for very dry to dry-combination skin. Step 3 of the 3-Step System.",
    isSeed: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: SEED_PRODUCT_IDS.cliniqueMoistureSurgeHydrator,
    name: "Moisture Surge 100H Auto-Replenishing Hydrator",
    brand: "Clinique",
    category: "moisturizer",
    ingredients: [
      "Water",
      "Dimethicone",
      "Glycerin",
      "Sodium Hyaluronate",
      "Aloe Barbadensis Leaf Extract",
      "Trehalose",
      "Saccharomyces Lysate Extract",
      "Magnesium Ascorbyl Phosphate",
      "Tocopheryl Acetate",
      "Caffeine",
    ],
    activeIngredients: ["hyaluronic acid", "vitamin c", "aloe"],
    usageGuide:
      "Apply a generous amount to clean, slightly damp skin morning and night. Press and pat into skin. In the morning, follow with SPF. Can also be used as a 5-minute hydrating mask.",
    frequency: "daily",
    timeOfDay: "any",
    notes: "Oil-free gel-cream with aloe bioferment and dual-weight hyaluronic acid.",
    isSeed: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: SEED_PRODUCT_IDS.cliniqueMoistureSurgeOvernight,
    name: "Moisture Surge Overnight Mask",
    brand: "Clinique",
    category: "mask",
    ingredients: [
      "Water",
      "Glycerin",
      "Dimethicone",
      "Butyrospermum Parkii (Shea) Butter",
      "Sodium Hyaluronate",
      "Aloe Barbadensis Leaf Water",
      "Panthenol",
      "Trehalose",
      "Mangifera Indica (Mango) Seed Butter",
      "Caffeine",
      "Bisabolol",
    ],
    activeIngredients: ["glycerin", "hyaluronic acid", "panthenol", "aloe"],
    usageGuide:
      "Use once daily as the last evening step. Apply liberally to face and throat; do not rinse. Leave on overnight and cleanse as usual in the morning.",
    frequency: "daily",
    timeOfDay: "evening",
    notes: "Oil-free overnight hydration mask. Use after moisturizer or as a moisture boost.",
    isSeed: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: SEED_PRODUCT_IDS.ceraveHydratingMineralSunscreen,
    name: "Hydrating Mineral Sunscreen SPF 30 Face Lotion",
    brand: "CeraVe",
    category: "sunscreen",
    ingredients: [
      "Titanium Dioxide 6%",
      "Zinc Oxide 5%",
      "Water",
      "Glycerin",
      "Niacinamide",
      "Ceramide NP",
      "Ceramide AP",
      "Ceramide EOP",
      "Sodium Hyaluronate",
      "Panthenol",
    ],
    activeIngredients: ["zinc oxide", "titanium dioxide", "niacinamide"],
    usageGuide:
      "Apply liberally 15 minutes before sun exposure as the final morning step. Rub between palms and massage in thoroughly to minimize white cast. Reapply at least every 2 hours.",
    frequency: "daily",
    timeOfDay: "morning",
    notes: "100% mineral, broad-spectrum SPF 30 with three essential ceramides.",
    isSeed: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: SEED_PRODUCT_IDS.freshSugarFacePolish,
    name: "Sugar Face Polish Exfoliator",
    brand: "Fresh",
    category: "exfoliant",
    ingredients: [
      "Sucrose",
      "Vitis Vinifera (Grape) Seed Oil",
      "Prunus Domestica (Plum) Seed Oil",
      "Fragaria Vesca (Strawberry) Fruit Extract",
      "Mangifera Indica (Mango) Seed Butter",
      "Tocopherol",
      "Glycerin",
    ],
    activeIngredients: ["vitamin c"],
    usageGuide:
      "After cleansing, apply to damp skin and massage in circular motions. Leave on 5–10 minutes, then rinse with warm water. Use 3–4 times per week; avoid on broken or irritated skin.",
    frequency: "weekly",
    timeOfDay: "evening",
    notes: "2-in-1 scrub and mask with brown sugar and strawberry extract.",
    isSeed: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: SEED_PRODUCT_IDS.medicubeZeroPorePad,
    name: "Zero Pore Pad 2.0",
    brand: "Medicube",
    category: "exfoliant",
    ingredients: [
      "Water",
      "Lactic Acid",
      "Salicylic Acid",
      "Betaine Salicylate",
      "Panthenol",
      "Glycerin",
      "Sodium Hyaluronate",
      "Centella Asiatica Extract",
      "Allantoin",
      "Trehalose",
    ],
    activeIngredients: ["lactic acid", "salicylic acid", "aha", "bha"],
    usageGuide:
      "After cleansing, swipe the embossed side across the face, then polish with the silky side. Start 2–3 nights per week and increase as tolerated. Follow with moisturizer; use SPF the next morning.",
    frequency: "weekly",
    timeOfDay: "evening",
    notes: "Dual-texture pads with 4.5% lactic acid and 0.45% BHA. Avoid layering with retinol or benzoyl peroxide.",
    isSeed: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: SEED_PRODUCT_IDS.medicubePdrnEyeMask,
    name: "PDRN Pink Collagen Jelly Eye Mask",
    brand: "Medicube",
    category: "eye_cream",
    ingredients: [
      "Water",
      "Glycerin",
      "Niacinamide",
      "Caffeine",
      "Hydrolyzed Collagen",
      "Sodium DNA",
      "Sodium Hyaluronate",
      "Panthenol",
      "Centella Asiatica Extract",
      "Squalane",
      "Tocopherol",
    ],
    activeIngredients: ["niacinamide", "caffeine", "hyaluronic acid"],
    usageGuide:
      "Apply hydrogel patches to clean, dry under-eye area for 20–30 minutes. Gently pat in remaining essence. Use 2–3 times per week or as needed for puffiness and hydration.",
    frequency: "weekly",
    timeOfDay: "any",
    notes: "PDRN, collagen, and caffeine hydrogel eye patches for depuffing and firming.",
    isSeed: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];

/** Seed products with catalog images, links, and commerce metadata. */
export const DEFAULT_PRODUCTS: Product[] = BASE_DEFAULT_PRODUCTS.map(
  (product) => enrichSeedProduct({ ...product, updatedAt: SEED_TIMESTAMP }),
);
